---
AWSTemplateFormatVersion: 2010-09-09
Description: Creates An RDS Instance for data refresh
Parameters:
  LifeCycle:
    Type: String
    Default: sbx
  DbSubnetGroup:
    Type: String
    Default: eqrs-sbx-rds-subnet-group
  DbUserName:
    Type: String
    Default: admin
  DbPassword:
    Type: String
    NoEcho: true
  ParameterGroupName:
    Type: String
    Default: default.oracle-ee-12.1
  SecurityGroup:
    Type: String
    Default: sg-05f1994a6be5239ee
  AllocatedStorage:
    Type: String
    Default: "20"
  KmsKeyId:
    Type: String
    Default: ""

Conditions:
  IsProd: !Or
    - !Equals
      - !Ref LifeCycle
      - "prod"
    - !Equals
      - !Ref LifeCycle
      - "prodpreview"

Resources:
  OracleRds:
    Type: 'AWS::RDS::DBInstance'
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${AWS::StackName}-oracle'
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: db.m4.large
      StorageType: gp2
      DBName: eqrs
      DBParameterGroupName: !Ref ParameterGroupName
      DBSubnetGroupName: !Ref DbSubnetGroup
      Engine: oracle-ee
      EngineVersion: 12.1.0.2.v18
      DeleteAutomatedBackups : true
      CopyTagsToSnapshot: true
      BackupRetentionPeriod: !If [ IsProd,  7, 1 ]
      AutoMinorVersionUpgrade: true
      LicenseModel: bring-your-own-license
      MasterUsername: !Ref DbUserName
      MasterUserPassword: !Ref DbPassword
      VPCSecurityGroups:
        - !Ref SecurityGroup
      EnableIAMDatabaseAuthentication: true
      MultiAZ: !If [ IsProd, true, false ]
      Port: '1521'
      DeletionProtection: true
      StorageEncrypted: true
      KmsKeyId: !ImportValue RdsKmsKeyArn
      MonitoringInterval: 5
      MonitoringRoleArn: !Join
        - ''
        - - 'arn:aws:iam::'
        - ':role/RDS_Enhanced_Monitoring'
      

